### 장소 생성
POST http://localhost:8080/place
Content-Type: application/json

{
   "name": "우리집"
  , "address": {
        "road": "도로명 주소"
        , "jibun": "지번 주소"
        , "zip": "06062"
        , "latitude": "128.6521583"
        , "longitude": "34.9070982"
  }
  , "categoryId": null
}

### 장소 조회
GET http://localhost:8080/place/1

###